export const QUESTIONS = [
    {
        lessonId: "user-res-1",
        question: "What is the main goal of user research in UI/UX design?",
        answers: [
            "To test software compilation speed",
            "To understand user behaviors, needs, and pain points",
            "To choose brand color schemes independently",
            "To write automated unit tests",
        ],
        correct: 1,
        explanation: "User research builds empathy and ensures product decisions are based on real user needs rather than assumptions.",
    },
    {
        lessonId: "user-res-2",
        question: "Which of the following is a qualitative research method?",
        answers: [
            "1-on-1 User Interviews",
            "Google Analytics traffic count",
            "A/B testing conversion rate",
            "SQL database performance logs",
        ],
        correct: 0,
        explanation: "User interviews collect non-numerical qualitative insights regarding feelings, thoughts, and user motivations.",
    },
    {
        lessonId: "user-res-3",
        question: "What is a User Persona?",
        answers: [
            "A real individual's personal social media profile",
            "A semi-fictional representation of your target user based on research data",
            "The founder of the design agency",
            "An automated bot for chat support",
        ],
        correct: 1,
        explanation: "User personas summarize common goals, behaviors, and pain points of target user segments.",
    },
    {
        lessonId: "user-res-4",
        question: "What is a Empathy Map used for?",
        answers: [
            "To visualize what a user says, thinks, does, and feels during an experience",
            "To calculate app loading times across regions",
            "To map database relationships between tables",
            "To draw high-fidelity interface wireframes",
        ],
        correct: 0,
        explanation: "Empathy maps help teams align on user perspectives by categorizing observable and implied behaviors.",
    },
    {
        lessonId: "user-res-5",
        question: "What distinguishes quantitative research from qualitative research?",
        answers: [
            "Quantitative measures numerical metrics; qualitative explores underlying reasons and emotions",
            "Quantitative is done after launch; qualitative is done only before launch",
            "Quantitative uses design tools; qualitative uses terminal commands",
            "There is no practical difference between them",
        ],
        correct: 0,
        explanation: "Quantitative answers 'how many' or 'how much', while qualitative answers 'why' or 'how'.",
    },
    {
        lessonId: "user-res-6",
        question: "What is a User Journey Map?",
        answers: [
            "A visual timeline mapping user steps, thoughts, and emotions to achieve a goal",
            "A GPS navigation screen layout",
            "A chart showing code release dates",
            "An internal employee org structure",
        ],
        correct: 0,
        explanation: "User journey mapping identifies key touchpoints, highs, and pain points across a complete workflow.",
    },
    {
        lessonId: "user-res-7",
        question: "When conducting user interviews, what type of questions should you primarily ask?",
        answers: [
            "Leading questions that encourage a specific answer",
            "Open-ended questions that encourage detailed storytelling",
            "Yes/No questions only",
            "Technical programming questions",
        ],
        correct: 1,
        explanation: "Open-ended questions prevent bias and invite participants to share authentic experiences.",
    },
    {
        lessonId: "user-res-8",
        question: "What is Card Sorting used for in user research?",
        answers: [
            "Sorting credit card payment processing options",
            "Understanding how users categorize and structure information logically",
            "Filtering search results by date",
            "Organizing design tokens in Figma",
        ],
        correct: 1,
        explanation: "Card sorting helps designers organize information architecture and navigation based on user mental models.",
    },
    {
        lessonId: "user-res-9",
        question: "What is a core advantage of contextual inquiry?",
        answers: [
            "Observing users in their real environment while performing actual tasks",
            "Generating color palettes automatically",
            "Running fast automated surveys without human interaction",
            "Reducing user research costs to zero",
        ],
        correct: 0,
        explanation: "Contextual inquiry reveals authentic habits and workaround behaviors that users might forget in an interview setting.",
    },
    {
        lessonId: "user-res-10",
        question: "What is the primary output of synthesizing user research findings?",
        answers: [
            "Actionable design requirements and problem statements",
            "Final production-ready React Native code",
            "Marketing ad campaigns",
            "Database migration scripts",
        ],
        correct: 0,
        explanation: "Synthesizing research turns raw data into key insights, problem definitions, and design opportunities.",
    },
];