export const QUESTIONS = [
    {
        lessonId: "wireframe-1",
        question: "What is the primary purpose of wireframing in UI design?",
        answers: [
            "To finalize colors, branding, and imagery",
            "To establish page layout, structural skeleton, and content hierarchy",
            "To optimize database queries for mobile apps",
            "To write production-ready CSS rules",
        ],
        correct: 1,
        explanation: "Wireframes focus on structure, space allocation, and content placement without visual design distractions.",
    },
    {
        lessonId: "wireframe-2",
        question: "What characterizes low-fidelity (Lo-Fi) wireframes?",
        answers: [
            "Pixel-perfect colors, real imagery, and realistic animations",
            "Simple sketches, basic shapes, and placeholder boxes focused on speed",
            "Fully interactive backend database integrations",
            "Finalized typography and exportable SVG assets",
        ],
        correct: 1,
        explanation: "Lo-Fi wireframes are quick, low-cost abstractions built to test concepts early.",
    },
    {
        lessonId: "wireframe-3",
        question: "Why are placeholders like gray boxes or 'Lorem Ipsum' used in wireframing?",
        answers: [
            "To avoid visual bias so feedback focuses on structural layout",
            "Because final copy is never written in UX projects",
            "To speed up CSS browser rendering engine performance",
            "Because colors are prohibited in mobile wireframing",
        ],
        correct: 0,
        explanation: "Placeholders keep stakeholders focused on functional layout rather than superficial styling details.",
    },
    {
        lessonId: "wireframe-4",
        question: "What is mid-fidelity wireframing primarily used for?",
        answers: [
            "Refining spatial layout, component sizing, and basic typography before high-fi design",
            "Writing server-side API endpoints",
            "Publishing directly to App Store production",
            "Generating color palettes automatically",
        ],
        correct: 0,
        explanation: "Mid-fidelity balances speed and clarity, providing precise layout details without full visual polish.",
    },
    {
        lessonId: "wireframe-5",
        question: "What is an Information Architecture (IA) map?",
        answers: [
            "A diagram illustrating structural organization and content hierarchy across a website or app",
            "A blueprint for cloud server hosting architecture",
            "A color swatch library in Figma",
            "An automated unit test suite in React Native",
        ],
        correct: 0,
        explanation: "IA maps depict how screens link together and how content is categorized across the application.",
    },
    {
        lessonId: "wireframe-6",
        question: "Which UI element is typically represented as a box with an 'X' inside in low-fidelity wireframes?",
        answers: [
            "Text paragraphs",
            "Image placeholders",
            "Primary CTA buttons",
            "Navigation header bars",
        ],
        correct: 1,
        explanation: "An 'X' inside a rectangle is the universal low-fidelity convention for image placeholders.",
    },
    {
        lessonId: "wireframe-7",
        question: "What is responsive wireframing?",
        answers: [
            "Designing layout variations across multiple device screen sizes (mobile, tablet, desktop)",
            "Making wireframes animate on click",
            "Writing responsive backend API microservices",
            "Automating dark mode color shifts",
        ],
        correct: 0,
        explanation: "Responsive wireframing plans how content elements adapt, stack, or reflow across different screen widths.",
    },
    {
        lessonId: "wireframe-8",
        question: "Why is sketching on paper or whiteboard valuable prior to digital wireframing?",
        answers: [
            "It allows rapid exploration of dozens of ideas in minutes with zero software friction",
            "It generates production CSS automatically",
            "It replaces the need for user testing completely",
            "It enforces strict pixel alignment from day one",
        ],
        correct: 0,
        explanation: "Paper sketching encourages rapid ideation without getting bogged down by digital tool constraints.",
    },
    {
        lessonId: "wireframe-9",
        question: "What is a wireflow?",
        answers: [
            "A combination of wireframe screens connected with arrows showing user interaction paths",
            "A CSS grid layout algorithm",
            "A database flow diagram",
            "A vector graphics rendering engine",
        ],
        correct: 0,
        explanation: "Wireflows illustrate both screen structure and dynamic screen-to-screen user flow navigation.",
    },
    {
        lessonId: "wireframe-10",
        question: "When should wireframing occur in a standard product design process?",
        answers: [
            "After final visual polish and branding are complete",
            "After user research and information architecture mapping, but before high-fidelity prototyping",
            "Only after the app is published to production",
            "During final database schema migration",
        ],
        correct: 1,
        explanation: "Wireframing bridges abstract research insights with concrete visual designs.",
    },
];